export const data = [
  {
    id: "10072",
    "Product Name": "Ebony - AAA (New Design)",
    "Scientific Name": "Diospyros ebenum",
    Origin: "Tropical regions",
    Type: "Artificial Veneer",
    Grades: "AAA",
    Sizes: "4x8 ft",
    Purpose: "Interior decoration, furniture",
    "Product Specification":
      "High-quality artificial veneer with a new design pattern, offering durability and aesthetic appeal.",
    Collection: "Exclusive Series",
    "Country of Origin": "Malaysia",
    Category: "artificial veneer",
    "Sizes Available": "4x8 ft, 4x10 ft",
    "Sub-category": "Decorative Veneer",
    Available: "Yes",
    "Grain Pattern Available": "Straight, Curly",
    Species: "Ebony",
    "Veneer Thickness": "0.5 mm",
    "Color Tone": "Dark Brown",
    Texture: "Smooth",
    "Veneer Cut": "Quarter Cut",
    "Polished/Unpolished": "Polished",
    "Botanical Name": "Diospyros ebenum",
    "Density (kg/m3)": "950",
    images: {
      img: [
        "/images/single/artificial/ebony-aaa-new-design/1.jpg",
        "/images/single/artificial/ebony-aaa-new-design/2.jpg",
      ],
    },
  },
  {
    id: "10073",
    "Product Name": "Ebony - ZZZ",
    "Scientific Name": "Diospyros ebenum",
    Origin: "Southeast Asia",
    Type: "Artificial Veneer",
    Grades: "ZZZ",
    Sizes: "4x8 ft",
    Purpose: "Luxury furniture, high-end interior finishes",
    "Product Specification":
      "Premium artificial veneer designed for top-tier applications, ensuring a rich appearance and long-lasting performance.",
    Collection: "Luxury Series",
    "Country of Origin": "Indonesia",
    Category: "artificial veneer",
    "Sizes Available": "4x8 ft, 5x10 ft",
    "Sub-category": "Premium Veneer",
    Available: "Yes",
    "Grain Pattern Available": "Straight, Swirl",
    Species: "Ebony",
    "Veneer Thickness": "0.6 mm",
    "Color Tone": "Jet Black",
    Texture: "Glossy",
    "Veneer Cut": "Flat Cut",
    "Polished/Unpolished": "Polished",
    "Botanical Name": "Diospyros ebenum",
    "Density (kg/m3)": "960",
    images: {
      img: [
        "/images/single/artificial/ebony-zzz/1.jpg",
        "/images/single/artificial/ebony-zzz/2.jpg",
      ],
    },
  },
  {
    id: "10074",
    "Product Name": "Ebony - QQQ",
    "Scientific Name": "Diospyros ebenum",
    Origin: "Africa",
    Type: "Artificial Veneer",
    Grades: "QQQ",
    Sizes: "4x8 ft",
    Purpose: "Cabinetry, architectural millwork",
    "Product Specification":
      "High-grade artificial veneer offering exceptional durability and a unique aesthetic for custom applications.",
    Collection: "Architectural Series",
    "Country of Origin": "Ghana",
    Category: "artificial veneer",
    "Sizes Available": "4x8 ft, 4x12 ft",
    "Sub-category": "Architectural Veneer",
    Available: "Yes",
    "Grain Pattern Available": "Wavy, Figured",
    Species: "Ebony",
    "Veneer Thickness": "0.7 mm",
    "Color Tone": "Rich Black",
    Texture: "Matte",
    "Veneer Cut": "Rotary Cut",
    "Polished/Unpolished": "Unpolished",
    "Botanical Name": "Diospyros ebenum",
    "Density (kg/m3)": "970",
    images: {
      img: [
        "/images/single/artificial/ebony-qqq/1.jpg",
        "/images/single/artificial/ebony-qqq/2.jpg",
      ],
    },
  },
  {
    id: "10075",
    "Product Name": "Ebony - Far",
    "Scientific Name": "Diospyros crassiflora",
    Origin: "West Africa",
    Type: "Artificial Veneer",
    Grades: "Far",
    Sizes: "4x8 ft",
    Purpose: "Wall panels, decorative surfaces",
    "Product Specification":
      "Versatile artificial veneer with a distinct design, ideal for enhancing modern interiors.",
    Collection: "Modern Series",
    "Country of Origin": "Cameroon",
    Category: "artificial veneer",
    "Sizes Available": "4x8 ft, 5x10 ft",
    "Sub-category": "Decorative Veneer",
    Available: "Yes",
    "Grain Pattern Available": "Crossfire, Plume",
    Species: "Ebony",
    "Veneer Thickness": "0.8 mm",
    "Color Tone": "Deep Black",
    Texture: "Semi-gloss",
    "Veneer Cut": "Rift Cut",
    "Polished/Unpolished": "Polished",
    "Botanical Name": "Diospyros crassiflora",
    "Density (kg/m3)": "980",
    images: {
      img: [
        "/images/single/artificial/ebony-far/1.jpg",
        "/images/single/artificial/ebony-far/2.jpg",
      ],
    },
  },
  {
    id: "10076",
    "Product Name": "Cherry Crown - AAA",
    "Scientific Name": "Prunus serotina",
    Origin: "North America",
    Type: "Artificial Veneer",
    Grades: "AAA",
    Sizes: "4x8 ft",
    Purpose: "High-end furniture, cabinetry",
    "Product Specification":
      "Top-quality artificial veneer with a beautiful cherry grain pattern, providing elegance and durability.",
    Collection: "Heritage Series",
    "Country of Origin": "United States",
    Category: "artificial veneer",
    "Sizes Available": "4x8 ft, 4x10 ft",
    "Sub-category": "Decorative Veneer",
    Available: "Yes",
    "Grain Pattern Available": "Crown, Cathedral",
    Species: "Cherry",
    "Veneer Thickness": "0.6 mm",
    "Color Tone": "Reddish Brown",
    Texture: "Smooth",
    "Veneer Cut": "Crown Cut",
    "Polished/Unpolished": "Polished",
    "Botanical Name": "Prunus serotina",
    "Density (kg/m3)": "700",
    images: {
      img: [
        "/images/single/artificial/cherry-crown-aaa/1.jpg",
        "/images/single/artificial/cherry-crown-aaa/2.jpg",
      ],
    },
  },
  {
    id: "10077",
    "Product Name": "Cherry Quarter - KK",
    "Scientific Name": "Prunus serotina",
    Origin: "North America",
    Type: "Artificial Veneer",
    Grades: "KK",
    Sizes: "4x8 ft",
    Purpose: "Paneling, bespoke furniture",
    "Product Specification":
      "High-quality artificial veneer with a distinct cherry quarter grain pattern, suitable for various decorative purposes.",
    Collection: "Elite Series",
    "Country of Origin": "Canada",
    Category: "artificial veneer",
    "Sizes Available": "4x8 ft, 4x12 ft",
    "Sub-category": "Decorative Veneer",
    Available: "Yes",
    "Grain Pattern Available": "Quarter, Ribbon",
    Species: "Cherry",
    "Veneer Thickness": "0.5 mm",
    "Color Tone": "Light Reddish Brown",
    Texture: "Matte",
    "Veneer Cut": "Quarter Cut",
    "Polished/Unpolished": "Unpolished",
    "Botanical Name": "Prunus serotina",
    "Density (kg/m3)": "720",
    images: {
      img: [
        "/images/single/artificial/cherry-quarter-kk/1.jpg",
        "/images/single/artificial/cherry-quarter-kk/2.jpg",
      ],
    },
  },
  {
    id: "10078",
    "Product Name": "Maple Crown - YYY",
    "Scientific Name": "Acer saccharum",
    Origin: "North America",
    Type: "Artificial Veneer",
    Grades: "YYY",
    Sizes: "4x8 ft",
    Purpose: "Custom cabinetry, interior decor",
    "Product Specification":
      "Premium artificial veneer with a striking maple crown grain pattern, perfect for high-end applications.",
    Collection: "Signature Series",
    "Country of Origin": "Canada",
    Category: "artificial veneer",
    "Sizes Available": "4x8 ft, 5x10 ft",
    "Sub-category": "Decorative Veneer",
    Available: "Yes",
    "Grain Pattern Available": "Crown, Burl",
    Species: "Maple",
    "Veneer Thickness": "0.6 mm",
    "Color Tone": "Light Cream",
    Texture: "Smooth",
    "Veneer Cut": "Crown Cut",
    "Polished/Unpolished": "Polished",
    "Botanical Name": "Acer saccharum",
    "Density (kg/m3)": "710",
    images: {
      img: [
        "/images/single/artificial/maple-crown-yyy/1.jpg",
        "/images/single/artificial/maple-crown-yyy/2.jpg",
      ],
    },
  },
  {
    id: "10079",
    "Product Name": "Teak Crown - SSS",
    "Scientific Name": "Tectona grandis",
    Origin: "Southeast Asia",
    Type: "Artificial Veneer",
    Grades: "SSS",
    Sizes: "4x8 ft",
    Purpose: "Luxury yacht interiors, high-end furniture",
    "Product Specification":
      "Luxurious artificial veneer featuring a prestigious teak crown grain pattern, crafted for elite interior designs.",
    Collection: "Yacht Series",
    "Country of Origin": "Indonesia",
    Category: "artificial veneer",
    "Sizes Available": "4x8 ft, 4x10 ft",
    "Sub-category": "Premium Veneer",
    Available: "Yes",
    "Grain Pattern Available": "Crown, Stripe",
    Species: "Teak",
    "Veneer Thickness": "0.8 mm",
    "Color Tone": "Golden Brown",
    Texture: "Satin",
    "Veneer Cut": "Crown Cut",
    "Polished/Unpolished": "Polished",
    "Botanical Name": "Tectona grandis",
    "Density (kg/m3)": "650",
    images: {
      img: [
        "/images/single/artificial/teak-crown-sss/1.jpg",
        "/images/single/artificial/teak-crown-sss/2.jpg",
      ],
    },
  },
  {
    id: "10080",
    "Product Name": "Zebrano - EXE",
    "Scientific Name": "Microberlinia brazzavillensis",
    Origin: "West Africa",
    Type: "Artificial Veneer",
    Grades: "EXE",
    Sizes: "4x8 ft",
    Purpose: "High-end furniture, interior accents",
    "Product Specification":
      "Exquisite artificial veneer with a distinctive zebrano grain pattern, ideal for creating bold interior statements.",
    Collection: "Signature Series",
    "Country of Origin": "Congo",
    Category: "artificial veneer",
    "Sizes Available": "4x8 ft, 5x10 ft",
    "Sub-category": "Decorative Veneer",
    Available: "Yes",
    "Grain Pattern Available": "Stripe, Wavy",
    Species: "Zebrano",
    "Veneer Thickness": "0.7 mm",
    "Color Tone": "Golden Yellow",
    Texture: "Satin",
    "Veneer Cut": "Quarter Cut",
    "Polished/Unpolished": "Polished",
    "Botanical Name": "Microberlinia brazzavillensis",
    "Density (kg/m3)": "670",
    images: {
      img: [
        "/images/single/artificial/zebrano-exe/1.jpg",
        "/images/single/artificial/zebrano-exe/2.jpg",
      ],
    },
  },
  {
    id: "10081",
    "Product Name": "Wenge Crown - AF",
    "Scientific Name": "Millettia laurentii",
    Origin: "Central Africa",
    Type: "Artificial Veneer",
    Grades: "AF",
    Sizes: "4x8 ft",
    Purpose: "High-end cabinetry, luxury interiors",
    "Product Specification":
      "Premium artificial veneer featuring a sophisticated wenge crown grain pattern, designed for exquisite interior applications.",
    Collection: "Luxury Series",
    "Country of Origin": "Gabon",
    Category: "artificial veneer",
    "Sizes Available": "4x8 ft, 4x10 ft",
    "Sub-category": "Premium Veneer",
    Available: "Yes",
    "Grain Pattern Available": "Crown, Mottle",
    Species: "Wenge",
    "Veneer Thickness": "0.6 mm",
    "Color Tone": "Dark Brown",
    Texture: "Matte",
    "Veneer Cut": "Crown Cut",
    "Polished/Unpolished": "Polished",
    "Botanical Name": "Millettia laurentii",
    "Density (kg/m3)": "850",
    images: {
      img: [
        "/images/single/artificial/wenge-crown-af/1.jpg",
        "/images/single/artificial/wenge-crown-af/2.jpg",
      ],
    },
  },
  {
    id: "10082",
    "Product Name": "Rosewood Quarter - TTT",
    "Scientific Name": "Dalbergia spp.",
    Origin: "Various regions (tropical)",
    Type: "Artificial Veneer",
    Grades: "TTT",
    Sizes: "4x8 ft",
    Purpose: "High-end furniture, musical instruments",
    "Product Specification":
      "Artificial veneer with a distinguished rosewood quarter grain pattern, suitable for luxurious interior applications.",
    Collection: "Premium Series",
    "Country of Origin": "Various",
    Category: "artificial veneer",
    "Sizes Available": "4x8 ft, 5x10 ft",
    "Sub-category": "Decorative Veneer",
    Available: "Yes",
    "Grain Pattern Available": "Quarter, Ribbon",
    Species: "Rosewood",
    "Veneer Thickness": "0.7 mm",
    "Color Tone": "Deep Brown",
    Texture: "Smooth",
    "Veneer Cut": "Quarter Cut",
    "Polished/Unpolished": "Polished",
    "Botanical Name": "Dalbergia spp.",
    "Density (kg/m3)": "800",
    images: {
      img: [
        "/images/single/artificial/rosewood-quarter-ttt/1.jpg",
        "/images/single/artificial/rosewood-quarter-ttt/2.jpg",
      ],
    },
  },
];
